platform :ios, '11.0'
use_frameworks!

target 'SoftSquared_w05_weather' do
  pod 'AFNetworking', '~> 2.6'
  pod 'ORStackView', '~> 3.0'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 5.0'
  pod 'SkeletonView'
end
